# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Ekin Gedik, Ph.D.
title: Postdoctoral researcher
email: e.gedik@tudelft.nl
address: VAN MOURIK BROEKMANWEG 6, 2628 XE DELFT, NETHERLANDS
#website: www.github.com/sproogen/resume-theme

# Social links
#github_username:  ekingedik
googlescholar_username: eg
#instagram_username: chillwildlife
linkedin_username: ekin-gedik-83748034
researchgate_username: Ekin_Gedik

# About Section
# about_title: About You
about_profile_image: images/eg.jpg
about_content: | # this will include new lines to allow paragraphs
 I am a computer scientist that aims to detect, analyse and enhance social experiences with the help of wearable sensing and machine learning. My expertise lies in automatic analysis of individual social behaviour, group interactions and how these concepts connect to the general social experience. I currently hold a post-doctoral researcher position in Socially Perceptive Computing Lab of TU Delft.
  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
